# Generated by Django 5.0.2 on 2024-02-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uniformresourcelocator",
            name="original_url",
            field=models.CharField(max_length=10000),
        ),
    ]
